import type { QuizStep } from '../../types';

export const quiz: QuizStep = {
  kind: 'quiz',
  id: 'quiz',
  title: 'Check your understanding',
  questions: [
    {
      id: 'q1',
      prompt:
        'An agent is asked to "add tests for `parsePagination`," which has a known off-by-one bug: it returns one extra page on the last batch. The agent reads the current implementation and writes tests that all pass immediately. What is the most accurate read of this test file?',
      choices: [
        { id: 'a', text: 'It is a good test file — every test passes, which means the function is verified.' },
        {
          id: 'b',
          text: 'It likely encodes the off-by-one bug as expected behavior, since the tests were generated by reading the implementation rather than a spec — a test derived from buggy code usually reproduces the bug, not catches it.',
        },
        { id: 'c', text: 'Green tests are always evidence of correctness regardless of how they were written.' },
      ],
      correctChoiceId: 'b',
      explanation:
        'Generating tests from the implementation means the test\'s expectation is "whatever the code currently does" — including bugs. Generating from a spec (what the function is supposed to do) is the only version that can fail against a buggy implementation, which is the entire point of a test.',
    },
    {
      id: 'q2',
      prompt:
        'A file has 100% line coverage and a 35% mutation score. What does that combination most precisely tell you?',
      choices: [
        { id: 'a', text: 'The two numbers are contradictory, so one of the tools is misconfigured.' },
        {
          id: 'b',
          text: 'Every line in the file runs during the test suite, but for roughly two-thirds of the small behavioral changes a bug could introduce, the tests would not notice — coverage measures execution, not verification.',
        },
        { id: 'c', text: 'The mutation score is irrelevant once coverage is at 100%.' },
      ],
      correctChoiceId: 'b',
      explanation:
        'Coverage and mutation score answer different questions. 100% coverage means every line executed at least once. A 35% mutation score means most single-line behavioral changes (mutants) survived the suite — the tests ran the code but weren\'t specific enough to catch it behaving differently.',
    },
    {
      id: 'q3',
      prompt:
        'A teammate runs Stryker on a function, sees a mutant survive that flips a boundary comparison (`<` to `<=`), and spends an hour writing more test cases trying to kill it, with no success. What is the most useful next step?',
      choices: [
        { id: 'a', text: 'Keep writing test cases indefinitely — a mutant that survives must mean the suite is incomplete.' },
        {
          id: 'b',
          text: 'Check whether the mutant is actually observable at all — some mutations produce code that behaves identically to the original for every input (an equivalent mutant), which Stryker\'s own docs describe as a known, unsolved limitation, and no test can ever kill one.',
        },
        { id: 'c', text: 'Delete the mutation testing config, since a surviving mutant means the tool is broken.' },
      ],
      correctChoiceId: 'b',
      explanation:
        'Not every mutant represents a real behavioral difference. An equivalent mutant is provably identical in observable behavior to the original for all inputs, so no test — however thorough — can ever distinguish them. Recognizing this caps expectations at less than 100% mutation score on some functions, rather than burning time chasing an unkillable mutant.',
    },
    {
      id: 'q4',
      prompt:
        'A custom multi-select combobox passes an axe-core scan with zero violations. A teammate wants to skip the manual accessibility pass because "the automated check is clean." What is the accurate response?',
      choices: [
        { id: 'a', text: 'Agree — a clean axe scan on a build that includes this component means it is fully accessible.' },
        {
          id: 'b',
          text: 'axe checks structural rules — valid ARIA, names, contrast — not behavior. Whether arrow keys move the active option, whether typing filters the list, and whether a screen reader announces the selection are not things axe can evaluate, and commonly-cited estimates put automated tools\' WCAG coverage at roughly half — the manual pass still needs to happen.',
        },
        { id: 'c', text: 'axe cannot scan custom components at all, so the zero-violations result is meaningless.' },
      ],
      correctChoiceId: 'b',
      explanation:
        'Automated accessibility tools operate on the accessibility tree and computed styles, which is why they are strong on presence-and-validity checks and blind to interaction behavior. A "clean scan" is a real, useful signal about a narrow slice of WCAG, not a substitute for testing the component\'s actual keyboard and screen-reader behavior.',
    },
    {
      id: 'q5',
      prompt:
        'An AI code review tool approves a PR that adds a retry loop around a payment API call, flagging no issues. A human reviewer, who knows the team had an incident six months ago from retrying a non-idempotent payment call, blocks it. What does this best illustrate about AI code review?',
      choices: [
        { id: 'a', text: 'AI review tools are not worth using, since they missed a real problem.' },
        {
          id: 'b',
          text: 'AI review is genuinely good at style and obvious bugs, but has no access to institutional context like a past incident — it reads the diff, not the history behind why a particular pattern is dangerous in this codebase. That kind of judgment is exactly what stacking a human review on top is for.',
        },
        { id: 'c', text: 'The human reviewer should defer to the AI tool\'s judgment, since it reviewed more of the codebase.' },
      ],
      correctChoiceId: 'b',
      explanation:
        'AI review tools work from the diff and general patterns, not from a team\'s specific incident history or product intent. This is exactly the blind spot human review depth should scale to cover, proportional to blast radius — and payment retry logic is about as high blast-radius as frontend code gets.',
    },
    {
      id: 'q6',
      prompt:
        'A team sets a hard CI gate: any PR that drops the mutation score below 80% fails the build. Six months later, the score sits steady at 81%, but a postmortem finds several recently-added tests that only exist to kill specific mutants and assert nothing else meaningful about behavior. What happened?',
      choices: [
        { id: 'a', text: 'Nothing concerning — a passing gate at 81% is proof the tests are good.' },
        {
          id: 'b',
          text: 'Goodhart\'s law: once mutation score became a hard target, the cheapest way to satisfy it — tests aimed at killing specific mutants rather than expressing real behavior — became attractive, which is the same failure mode the metric was introduced to catch, one level removed. The gate should feed a human conversation about trend, not stand alone as the only pass/fail signal.',
        },
        { id: 'c', text: 'This means mutation testing is fundamentally not a useful technique and should be dropped.' },
      ],
      correctChoiceId: 'b',
      explanation:
        'Any metric that becomes the target stops being a reliable measure. A hard mutation-score gate can be satisfied by narrowly-targeted, low-value tests just as easily as a coverage gate can be satisfied by tests with no real assertions. The fix isn\'t abandoning the metric — it\'s keeping a human in the loop on what "kill this mutant" tests are actually verifying.',
    },
  ],
};
